### ISSUE TITLE
Error regarding quota

### ISSUE THREAD

**Issue by exactt** [Schluggi/pymap-copy#11]
Hi,

I get the following error: 

Getting source quota        : Traceback (most recent call last):
  File "./pymap-copy.py", line 161, in <module>
    source_quota = source.get_quota()[0]
IndexError: list index out of range

I commented the line(s) out but wanted to let you know anyway.

Thx

**Comment by Schluggi** [comment]
Could you edit this line as shown below and post the output?
```
source_quota = source.get_quota()
print(source_quota, type(source_quota))
```

The `get_quota()` function should return a list. In your case you got something else. So I'm interested in the response.

**Comment by Schluggi** [comment]
No response after 1 month. Closing.

**Comment by loveJesus** [comment]
Hallelujah, thanks for this program. Getting a similar error on line 33 which is called from line 245 calling with 'Quota(quota_root='Mailbox', resource='MESSAGE', usage=9, limit=2147483647)' if it is any help

**Comment by Schluggi** [comment]
Thank you for reporting. Should be fixed 🙂
