### ISSUE TITLE
"logging" is missing

### ISSUE THREAD

**Issue by To3No7** [Schluggi/pymap-copy#25]
It seems that there is a missing definition of logging:
```
Getting source quota        : Traceback (most recent call last):
  File "/usr/local/Caskroom/miniforge/base/bin/pymap-copy.py", line 273, in <module>
    logging.info(f'Getting source quota...')
NameError: name 'logging' is not defined
```

**Comment by To3No7** [comment]
I believe you are missing an `import logging` in the beginning.

**Comment by Schluggi** [comment]
I agree with you and your solution but I wonder why I never got these error.

I'll fix it. Thank you for reporting :)
